//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeletieneDPS.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class qualificationps
    {
        public int id { get; set; }
        public Nullable<int> idproduct { get; set; }
        public string comment { get; set; }
        public int value { get; set; }
        public System.DateTime dateup { get; set; }
    
        public virtual productservice productservice { get; set; }
    }
}
